version: '3'

services:
  freeipa:
    image: freeipa/freeipa-server:centos-7
    container_name: freeipa
    hostname: freeipa.uucin.com
    sysctls:
      net.core.somaxconn: '65535'
      net.ipv6.conf.all.disable_ipv6: '0'
    command:
      - ipa-server-install 
      - -U 
      - -r UUCIN.COM
      - --no-ntp
    environment:
      PASSWORD: "2239a03393394db699a0fff36db7eeb7"
    ports:
      - 80:80/tcp
      - 88:88/udp
      - 88:88/tcp
      - 389:389/tcp
      - 443:443/tcp
      - 123:123/udp
      - 464:464/tcp
      - 636:636/tcp
      - 464:464/udp
    volumes:
      - $PWD/ipa-data:/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    restart: always
    network_mode: host
